name: CMake-Windows

on:
  push:
    branches:
      - v1.2.0-build

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    # cache/install dependencies
    # see - https://raymii.org/s/articles/Github_Actions_cpp_boost_cmake_speedup.html

    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_INSTALL_PREFIX=./release -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --target install --config $BUILD_TYPE

    - name: Create Artifact
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        ls -ls ./
        ls -ls ./build/release
        zip -r release-windows.zip build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: release-windows
        path: ${{github.workspace}}/release-windows.zip
